namespace FreeRoamProject.Client.Core.Utility
{
    public enum FE_WARNING_FLAGS
    {
        FE_WARNING_NONE = 0,

        FE_WARNING_SELECT = 1,
        FE_WARNING_OK = 1 << 1,
        FE_WARNING_YES = 1 << 2,
        FE_WARNING_BACK = 1 << 3,
        FE_WARNING_CANCEL = 1 << 4,
        FE_WARNING_NO = 1 << 5,
        FE_WARNING_RETRY = 1 << 6,
        FE_WARNING_RESTART = 1 << 7,
        FE_WARNING_SKIP = 1 << 8,
        FE_WARNING_QUIT = 1 << 9,
        FE_WARNING_ADJUST_LEFTRIGHT = 1 << 10,
        FE_WARNING_IGNORE = 1 << 11,
        FE_WARNING_FACEBOOK_SHARE = 1 << 12,
        FE_WARNING_SIGNIN = 1 << 13,
        FE_WARNING_CONTINUE = 1 << 14,
        FE_WARNING_OVERWRITE = 1 << 15,
        FE_WARNING_SC_SIGNUP = 1 << 16,
        FE_WARNING_ENTER_QUEUE = 1 << 17,
        FE_WARNING_RETRY_A = 1 << 18,
        FE_WARNING_BACK_WITH_ACCEPT_SOUND = 1 << 19,
        FE_WARNING_SC_UPDATE = 1 << 20, // For when the policies are out of date.
        FE_WARNING_ENTER_SPEC = 1 << 21,
        FE_WARNING_OKBACK = 1 << 22,
        FE_WARNING_CANCEL_TRANSFER = 1 << 23,
        FE_WARNING_SPINNER_ONLY = 1 << 24,
        FE_WARNING_RETURNSP = 1 << 25,
        FE_WARNING_CANCEL_ON_B = 1 << 26,

        // Use this flag to suppress sound input
        // Probably because you're using JUST_PRESSED instead of the UI standard JUST_RELEASED, so sound will be wonky.
        FE_WARNING_NOSOUND = 1 << 27,
        //FE_WARNING_EXIT		= BIT31


        // ABOVE IS READ FROM FRONTEND.XML
        // YOU CAN ADD MORE, BUT MAKE SURE THEY MATCH

        // feel free to modify these for common constructions
        FE_WARNING_YESNO = FE_WARNING_YES + FE_WARNING_NO,
        FE_WARNING_OKCANCEL = FE_WARNING_OK + FE_WARNING_CANCEL,
        FE_WARNING_OKCANCELRETRY = FE_WARNING_OKCANCEL + FE_WARNING_RETRY,
        FE_WARNING_OKSHARE = FE_WARNING_OK + FE_WARNING_FACEBOOK_SHARE,
        FE_WARNING_OKRETRY = FE_WARNING_OK + FE_WARNING_RETRY,
        FE_WARNING_OKSIGNIN = FE_WARNING_OK + FE_WARNING_SIGNIN,
        FE_WARNING_CANCELSIGNIN = FE_WARNING_CANCEL + FE_WARNING_SIGNIN,
        FE_WARNING_CANCELOVERWRITERETRY = FE_WARNING_CANCEL + FE_WARNING_OVERWRITE + FE_WARNING_RETRY_A,
        FE_WARNING_CONTINUEBACK = FE_WARNING_CONTINUE + FE_WARNING_BACK,
        FE_WARNING_CONTINUESAVECANCELRETRY = FE_WARNING_CONTINUE + FE_WARNING_CANCEL + FE_WARNING_RETRY,
        FE_WARNING_CONTINUERETURNSP = FE_WARNING_CONTINUE + FE_WARNING_RETURNSP,
        FE_WARNING_RETRYCONTINUE = FE_WARNING_RETRY + FE_WARNING_CONTINUE,
        FE_WARNING_YESRETURNSP = FE_WARNING_YES + FE_WARNING_RETURNSP,
        FE_WARNING_FULL_SESSION_BOTH = FE_WARNING_ENTER_SPEC + FE_WARNING_ENTER_QUEUE + FE_WARNING_CANCEL,
        FE_WARNING_SELECTCANCEL = FE_WARNING_SELECT + FE_WARNING_CANCEL
    }
}